= Decaland Touchstone
:url-gradle-composite: https://docs.gradle.org/current/userguide/composite_builds.html
:toc: preamble

Custom Gradle plugins that provide the common build configuration for Decaland applications.

The usage of Touchstone plugins is exemplified by the sub-project `dcl-tabula`, included as part of {url-gradle-composite}[Gradle composite build].
To create a project based on Touchstone plugins:

* either copy project structure/configuration from `dcl-tabula`,
* or use the `create_decaland_service.sh` script, documented <<create-service,below>>.

== Provided Gradle plugins

=== Artifact type plugins

Only one of these plugins can be applied to a given build.

Each of them configures the build to produce a certain kind of publishable artifact: either a library (pulled by other projects as a dependency), or an application (executed and not depended upon).
The plugins also provision a layer of essential dependencies, e.g., the Kotlin standard library for Kotlin builds, or the Spring Boot basic starter for the builds that employ the framework.

[horizontal]
`*dcl-lib-java*`::
a *library* written in pure Java.
`*dcl-lib-java-kotlin*`::
a *library* written in Java, Kotlin, or mix thereof.
`*dcl-boot-lib-java*`::
a Spring Boot-based *library* written in pure Java.
`*dcl-boot-lib-java-kotlin*`::
a Spring Boot-based *library* written in Java, Kotlin, or mix thereof.
`*dcl-boot-app-java*`::
a Spring Boot-based bootable *application* written in pure Java.
`*dcl-boot-app-java-kotlin*`::
a Spring Boot-based bootable *application* written in Java, Kotlin, or mix thereof.

=== Dependency collection plugins

Each of these plugins defines a homogenous set of dependencies, grouped by a use-case, or a certain development approach.
Unless noted otherwise, any combination of these can be applied.

[horizontal]
`*dcl-uses-junit-five*`::
testing infrastructure centered on jUnit5.
== [[create-service]] How to use

Run the provided `create_decaland_service.sh` script from the root of the  repository:

[source,bash]
----
./create_decaland_service.sh <SERVICE_NAME> \
    --pretty-name <PRETTY_NAME> \
    --package-name <PACKAGE_NAME>
----

This helper script prints its intentions and prompts for confirmation _before_ introducing any changes.

* The `<SERVICE_NAME>` should be a kebab-case identifier, e.g., `super-service`.
** The `dcl-` prefix is added automatically, and all characters are made lowercase.
* The `<PRETTY_NAME>` should be a human-readable name, e.g., `Super Service`.
** The full name is prefixed with the word ‘Decaland,’ e.g., ‘Decaland Super Service.’
** If not provided, the pretty name is generated by taking the service name, substituting dashes for spaces, and capitalizing first letters of every word.
* The `<PACKAGE_NAME>` should be the name of the root Java package, e.g., `superservice`.
** Only lowercase ASCII letters are allowed.
** The package is put directly under `com.github.decaland`.
** If not provided, the package name is generated by taking the service name and dropping all dashes.

The script creates the resulting project in a sibling directory to the one containing the helper.
In that new directory, the `git init .` command is run, but the initial commit is _not_ performed.

The full usage hint for the script is:

[source]
----
./create_decaland_service.sh <SERVICE_NAME> [-h|--pretty-name <PRETTY_NAME>] [-p|--package-name <PACKAGE_NAME>]
----

=== Example usage

[source]
----
/home/user/decaland/dcl-touchstone $ ./create_decaland_service.sh super-service

About to create a new Decaland service:
Service path      : /home/user/decaland/dcl-super-service
Service name      : dcl-super-service
Pretty name       : Decaland Super Service
Root Java package : com.github.decaland.superservice
Proceed? (y/n)
----

== Maintenance

The sub-project `dcl-tabula` is included as part of {url-gradle-composite}[Gradle composite build] and is thus more or less independent.
Once a new version of `dcl-touchstone` is released, `dcl-tabula` should be:

* upgraded to use that new Touchstone version,
* built via Gradle (as a sanity check),
* and committed to version control.

== Project structure

* `./buildSrc/` — This directory is a hack.
It allows applying the standalone Gradle plugins developed within this project onto this project itself.
* `./dcl-tabula/` — This directory contains a blank sample project that exemplifies the intended usage of the Touchstone plugins.
* `./src/` — the actual code of the Touchstone plugins.
