= Decaland Touchstone
:url-gradle-composite: https://docs.gradle.org/current/userguide/composite_builds.html

Custom Gradle plugins that provide the common build configuration for Decaland applications.

== Usage

The usage of Touchstone plugins is exemplified by the sub-project `dcl-tabula`, included as part of {url-gradle-composite}[Gradle composite build].
To create a project based on Touchstone plugins:

* either copy project structure/configuration from `dcl-tabula`,
* or use the `create_decaland_service.sh` script, which is documented in the `dcl-tabula`’s README file.

== Provided Gradle plugins

The following Touchstone plugins are available and provide their described build configuration (only one of these can be applied at a time):

[horizontal]
`*dcl-lib-java*`::
libraries written in pure Java.
`*dcl-lib-java-kotlin*`::
libraries written in Java, Kotlin, or mix thereof.
`*dcl-boot-lib-java*`::
Spring Boot-based libraries written in pure Java.
`*dcl-boot-lib-java-kotlin*`::
Spring Boot-based libraries written in Java, Kotlin, or mix thereof.
`*dcl-boot-app-java*`::
Spring Boot-based _bootable applications_ written in pure Java.
`*dcl-boot-app-java-kotlin*`::
Spring Boot-based _bootable applications_ written in Java, Kotlin, or mix thereof.

Along with any of the build configurations above, the consumer might want to also apply library dependencies via additional Touchstone plugins:

[horizontal]
`*dcl-uses-junit-five*`::
testing dependencies centered on jUnit5.

== Maintenance note

The sub-project `dcl-tabula` is included as part of {url-gradle-composite}[Gradle composite build] and is thus more or less independent.
Once a new version of `dcl-touchstone` is released, `dcl-tabula` should be:

* upgraded to use that new version,
* built via Gradle (as a sanity check),
* and committed to version control.
