= Decaland Touchstone

This project implements custom Gradle plugins that provide the common build configuration for Decaland applications.

== Usage

To use the `dcl-touchstone` foundation, add the following files to the consumer project:

* `gradle.properties` (in the root of the consumer project)
+
[source,properties]
----
# ... consumer project’s `version` probably goes here ...

dcl.version.touchstone = 0.1.2-SNAPSHOT

systemProp.org.gradle.internal.publish.checksums.insecure = true
----
+
Use the latest stable version of the `dcl-touchstone` project.
The long-winded property at the end is optional: it makes Gradle publish https://docs.gradle.org/6.0.1/release-notes.html[insecure checksums] to prevent warnings from the current version of Serpnet Artifactory.
* `settings.gradle` (in the root of the consumer project)
+
[source,groovy]
----
pluginManagement {
    plugins {
        id 'dcl-lib-java' version "${getProperty('dcl.version.touchstone')}"
        id 'dcl-lib-java-kotlin' version "${getProperty('dcl.version.touchstone')}"
        id 'dcl-boot-lib-java' version "${getProperty('dcl.version.touchstone')}"
        id 'dcl-boot-lib-java-kotlin' version "${getProperty('dcl.version.touchstone')}"
        id 'dcl-boot-app-java' version "${getProperty('dcl.version.touchstone')}"
        id 'dcl-boot-app-java-kotlin' version "${getProperty('dcl.version.touchstone')}"
        id 'dcl-essential-dependencies' version "${getProperty('dcl.version.touchstone')}"
    }
    repositories {
        maven { url 'https://serpnet.jfrog.io/artifactory/decaland-maven-releases' }
        maven { url 'https://serpnet.jfrog.io/artifactory/decaland-maven-snapshots' }
        gradlePluginPortal()
        mavenCentral()
        mavenLocal()
    }
}

// ... `rootProject.name`, `include`, and so on ...
----
* In each build module the Touchstone plugins can be applied by including them in the `build.gradle` file, e.g.:
+
[source,groovy]
----
plugins {
    id 'dcl-lib-java'
    id 'dcl-essential-dependencies'
}

// ... `group` and so on ...
----

== Provided Gradle plugins

The following Gradle plugins are available and provide their described build configuration (only one of these can be applied at a time):

[horizontal]
`*dcl-lib-java*`:: libraries written in pure Java.
`*dcl-lib-java-kotlin*`:: libraries written in Java, Kotlin, or mix thereof.
`*dcl-boot-lib-java*`:: Spring Boot-based libraries written in pure Java.
`*dcl-boot-lib-java-kotlin*`:: Spring Boot-based libraries written in Java, Kotlin, or mix thereof.
`*dcl-boot-app-java*`:: Spring Boot-based _bootable applications_ written in pure Java.
`*dcl-boot-app-java-kotlin*`:: Spring Boot-based _bootable applications_ written in Java, Kotlin, or mix thereof.

Along with any of the build configurations above, the consumer might want to also apply a small set of basic library dependencies via the additional Gradle plugin:

[horizontal]
`*dcl-essential-dependencies*`:: provides `lombok` to all projects; `kotlin-stdlib` and `kotlin-reflect` to projects that use Kotlin; and `spring-boot-starter-test` to Spring Boot-based projects.
