= Decaland Tabula (sample project)

A blank sample project to be used as a template for new Decaland microservices.
Includes three sub-projects:

- `app`: the executable application,
- `client`: the consumable library that provides ways to consume the application's public API,
- `model`: the consumable library that provides models that are part of the application's public API.

This sample project is included inside (and version-controlled along with) its parent project, `dcl-touchstone`.
The Touchstone Gradle plugins are the basis of Decaland services, and this sample project illustrates the proper usage thereof.

== How to use

Run the provided Bash script from the root of the parent repository, `dcl-touchstone`:

[source,bash]
----
./create_decaland_service.sh <SERVICE_NAME> \
    --pretty-name <PRETTY_NAME> \
    --package-name <PACKAGE_NAME>
----

The script prints its intentions to console, then prompts for confirmation before introducing any changes.

* The `<SERVICE_NAME>` should be a kebab-case identifier, e.g., `super-service`.
** The `dcl-` prefix is added automatically, and all characters are made lowercase.
* The `<PRETTY_NAME>` should be a human-readable name, e.g., `Super Service`.
** The full name is prefixed with the word ‘Decaland,’ e.g., ‘Decaland Super Service.’
** If not provided, the pretty name is generated by taking the service name, substituting dashes for spaces, and capitalizing first letters of every word.
* The `<PACKAGE_NAME>` should be the name of the root Java package, e.g., `superservice`.
** Only lowercase ASCII letters are allowed.
** The package is put directly under `com.github.decaland`.
** If not provided, the package name is generated by taking the service name and dropping all dashes.

The resulting project is created as a sibling directory to the one containing `dcl-touchstone`.
In the new directory, the `git init .` command is run, but the initial commit is left to the author.

The full usage hint for the script is:

[source]
----
./create_decaland_service.sh <SERVICE_NAME> [-h|--pretty-name <PRETTY_NAME>] [-p|--package-name <PACKAGE_NAME>]
----
